// filePath src/app/layout.tsx
import AuthContextFunc from "@/context/1-auth-context";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContextFunc>{children}</AuthContextFunc>
      </body>
    </html>
  );
}
